'use strict';
const $=id=>document.getElementById(id), key='saniya-qa-cases-v1';
let cases=[],editId=null;
function status(message){$('editor-status').textContent=message;}
function persist(){try{localStorage.setItem(key,JSON.stringify(cases));$('draft-state').textContent='Draft saved in this browser only. Export to update your published suite.';}catch{$('draft-state').textContent='Browser storage is unavailable. Export to keep your cases before leaving.';}}
function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function render(){const body=$('case-list');body.replaceChildren();for(const c of cases){const row=document.createElement('tr'),title=node('td',c.title);title.append(node('small',c.id));row.append(title);const target=node('td',c.path);target.append(node('small',c.selector));row.append(target,node('td',c.assertion+(c.expected?' → '+c.expected:'')));const actions=node('td','');for(const [label,fn] of [['Edit',()=>{editId=c.id;for(const [k,v]of Object.entries(c))if($('case-form').elements.namedItem(k))$('case-form').elements.namedItem(k).value=v;$('editor-title').textContent='Edit '+c.id;$('cancel').hidden=false;$('case-form').elements.namedItem('title').focus();}],['Remove',()=>{cases=cases.filter(x=>x.id!==c.id);if(editId===c.id)cancel();persist();render();}]]){const b=node('button',label);b.type='button';b.setAttribute('aria-label',label+' '+c.id);b.onclick=fn;actions.append(b);}row.append(actions);body.append(row);}}
function cancel(){editId=null;$('case-form').reset();$('editor-title').textContent='Add a test case';$('cancel').hidden=true;}
$('cancel').onclick=cancel;
$('case-form').onsubmit=e=>{e.preventDefault();const c=Object.fromEntries(new FormData(e.target));for(const k in c)c[k]=c[k].trim();try{const next=cases.filter(x=>x.id!==editId);next.push(c);validateCases(next);cases=next;persist();render();cancel();status('Case saved. Export and commit cases.json before starting a run.');}catch(err){status(err.message);}};
$('export').onclick=()=>{try{validateCases(cases);const url=URL.createObjectURL(new Blob([JSON.stringify(cases,null,2)],{type:'application/json'}));const a=node('a','');a.href=url;a.download='cases.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Exported. Upload this file to the repository root as cases.json.');}catch(err){status(err.message);}};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>250000)throw Error('Choose a JSON file smaller than 250 KB.');const next=validateCases(JSON.parse(await f.text()));cases=next;cancel();persist();render();status('Cases imported into this browser draft.');}catch(err){status('Import failed: '+err.message);}e.target.value='';};
async function results(){const b=$('refresh');b.disabled=true;try{const res=await fetch('qa-results/latest.json',{cache:'no-store'});if(!res.ok)throw Error('No report is available yet.');const data=await res.json();if(!data.generatedAt||!Array.isArray(data.tests))throw Error('No published run yet. Commit the workflow and run it in GitHub Actions.');$('run-meta').textContent=new Date(data.generatedAt).toLocaleString()+' · Commit '+data.commit.slice(0,7)+' · '+data.status;$('total').textContent=data.tests.length;$('passed').textContent=data.tests.filter(t=>t.status==='passed').length;$('failed').textContent=data.tests.filter(t=>!['passed','skipped'].includes(t.status)).length;$('duration').textContent=(data.duration/1000).toFixed(1)+'s';$('result-list').replaceChildren();for(const t of data.tests){const row=node('div','');row.className='qa-result';row.dataset.status=t.status;const label=node('div',t.title);label.append(node('small',t.error||'Recorded by Playwright'));row.append(label,node('b',t.status+' · '+(t.duration/1000).toFixed(2)+'s'));$('result-list').append(row);}$('report-link').hidden=false;}catch(err){$('run-meta').textContent=location.protocol==='file:'?'Open the hosted page to load committed cases and published results. No tests have run in this preview.':err.message;}finally{b.disabled=false;}}
$('refresh').onclick=results;
(async()=>{try{let saved;try{saved=localStorage.getItem(key);}catch{}if(saved){cases=validateCases(JSON.parse(saved));$('draft-state').textContent='Loaded your local draft; it may differ from the committed suite.';}else{const r=await fetch('cases.json');if(!r.ok)throw Error('Cases could not load.');cases=validateCases(await r.json());$('draft-state').textContent='Committed starter cases. Edits are drafts until exported and committed.';}render();}catch{status('Import cases.json from the downloaded package, or add your first case.');}await results();})();
